assertion "may throw exception" returned TypeError.*for value undefined
